# Change prompt
export PS1="Test$ "

# Add the Server binaries to the PATH
#PATH=$PATH:$HOME/server:$HOME/server/tools:$HOME/server/tools/configurebasedeployment

TOOLS=$HOME/arcgis/notebookserver/tools
PATH=$PATH:$HOME/server:$TOOLS
#PATH="${PATH}:$(find $HOME/server/tools -type d -printf ':%p')"

for d in "$TOOLS"/* ; do
    if [ -d "$d" ]; then
        PATH="$PATH:$d"
    fi
done
export PATH