volumes:
#
# *_home volumes are the /home/arcgis directories
# and the software for each service gets installed there.
#
# *_data volumes are where the data for each services gets stored.
#
  portal_home:
    name: arcgis_portal_home
  portal_data:
    name: arcgis_portal_data
  server_home:
    name: arcgis_server_home
  server_data:
    name: arcgis_server_data
  datastore_home:
    name: arcgis_datastore_home
  datastore_data:
    name: arcgis_datastore_data
  postgres_data:
    name: arcgis_postgres_data
  pgadmin_data:
    name: arcgis_pgadmin_data
  test_home:
    name: arcgis_test_home
  test_data:
    name: arcgis_test_data

networks:
  mynetwork:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "0.0.0.0"
    ipam:
      config:
        - subnet: 172.31.0.0/24
          gateway: 172.31.0.1

services:
  server:
    image: arcgis-server
    extra_hosts:
      - "host.docker.internal:host-gateway"
    cap_add:
      - NET_ADMIN
      - SYS_TIME
    container_name: ag-server
    networks:
      mynetwork:
        ipv4_address: 172.31.0.10
        mac_address: "02:42:ac:14:00:0a" # Note: MAC addresses should be within the Docker-assigned range for bridge networks
    hostname: ${GISSERVER}
    build: 
      context: ./server
      dockerfile: Dockerfile
    env_file: ./.env
    environment:
      - ESRI_VERSION=${ESRI_VERSION}
      - AGS_USERNAME=${USERNAME}
      - AGS_PASSWORD=${PASSWORD}
      - KEYCODES_PATH=/home/arcgis/server/framework/runtime/.wine/drive_c/Program Files/ESRI/License${ESRI_VERSION}/sysgen/keycodes
    ports:
      - "6080:6080"
      - "6443:6443"
    volumes:
      - ./Installers/ArcGISServer:/app/Installer:ro
      - ./Licenses:/app/licenses
     #- ./Licenses/server.prvc:/app/server.prvc:ro
      - ./configurebasedeployment.properties:/app/configurebasedeployment.properties:rw
      - "./shared/server:/shared:rw"
      - "./ubuntu-server/charles.pem:/tmp/charles.pem:ro"
      - server_home:/home/arcgis:rw
      - server_data:/srv/directories:rw
#      - server_config:/home/arcgis/server/usr/config-store
#      - server_logs:/home/arcgis/server/usr/logs
    # Uncomment the next three lines to work in a shell environment for debugging. (See exec_server)
    #entrypoint: /bin/bash
    #stdin_open: true
    #tty: true

  portal:
    image: arcgis-portal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    cap_add:
      - NET_ADMIN
      - SYS_TIME
    container_name: ag-portal
    networks:
      mynetwork:
        ipv4_address: 172.31.0.11
        mac_address: "02:42:ac:14:00:0b"
    hostname: ${PORTAL}
    build:
      context: ./portal
      dockerfile: Dockerfile
    env_file: ./.env
    environment:
      - ESRI_VERSION=${ESRI_VERSION}
      - AGP_USERNAME=${USERNAME}
      - AGP_PASSWORD=${PASSWORD}
      - PORTAL_CONTENT=/srv/content
    ports:
      - "7080:7080"
      - "7443:7443"
    volumes:
      - ./Installers/PortalForArcGIS:/app/Installer:ro
      - ./Licenses:/app/licenses
     #- ./Licenses/portal.json:/app/portal_license.json:ro
      - "./shared/portal:/shared:rw"
      - "./ubuntu-server/charles.pem:/tmp/charles.pem:ro"
      - portal_home:/home/arcgis:rw
      - portal_data:/home/arcgis/content:rw
     #- portal_data:/home/arcgis/portal/usr/arcgisportal:rw
    links:
      - server
      - datastore
    # Uncomment the next three lines to work in a shell environment for debugging.
#    entrypoint: /bin/bash
#    stdin_open: true
#    tty: true

  datastore:
    image: arcgis-datastore
    extra_hosts:
      - "host.docker.internal:host-gateway"
    cap_add:
      - NET_ADMIN
      - SYS_TIME
    container_name: ag-datastore
    networks:
      mynetwork:
        ipv4_address: 172.31.0.12
        mac_address: "02:42:ac:14:00:0c"
    hostname: ${DATASTORE}
    build: 
      context: ./datastore
      dockerfile: Dockerfile
    env_file: ./.env
    environment:
      - ESRI_VERSION=${ESRI_VERSION}
      - AGE_SERVER=${GISSERVER}
      - AGS_USERNAME=${USERNAME}
      - AGS_PASSWORD=${PASSWORD} 
    ports:
      - "2443:2443"
      - "9876:9876"
    volumes:
      - ./Installers/DataStore:/app/Installer:ro
      - "./ubuntu-server/charles.pem:/tmp/charles.pem:ro"
      - datastore_home:/home/arcgis:rw
# where does this belong
#      - datastore_data:/home/arcgis/?????:rw
    links:
      - server
    # Uncomment the next three lines to work in a shell environment for debugging.
    #entrypoint: /bin/bash
    #stdin_open: true
    #tty: true

  postgres:
    image: postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - mynetwork
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
      # Allow access to this database from our LAN
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  pgadmin:
    image: dpage/pgadmin4:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - mynetwork
    ports:
      - "8213:80"
    volumes:
      # Session data, user files, config files, config database go here.
      - pgadmin_data:/var/lib/pgadmin
    env_file: .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_DISABLE_POSTFIX: 1

  test:
    image: arcgis-test
    # cgroup: host
    extra_hosts:
      - "host.docker.internal:host-gateway"
      # - "${PORTAL}:host-gateway"
    cap_add:
      - NET_ADMIN
      # - SYS_ADMIN
      - SYS_TIME
    container_name: ag-test
    network_mode: "host"
    #networks:
    #  - mynetwork
    #     ipv4_address: 172.31.0.10
    #     mac_address: "02:42:ac:14:00:0a" # Note: MAC addresses should be within the Docker-assigned range for bridge networks
    #hostname: test.local
    build:
      context: ./test
      dockerfile: Dockerfile
    env_file: ./.env
    environment:
      - ESRI_VERSION=${ESRI_VERSION}
      - AGS_USERNAME=${USERNAME}
      - AGS_PASSWORD=${PASSWORD}
      - KEYCODES_PATH=/home/arcgis/arcgis/notebookserver/framework/runtime/.esri/License${ESRI_VERSION}/sysgen/keycodes
    ports:
      - "11443:11443"
      #- "10.42.0.13:30001-30010:30001-30010"
    volumes:
      - ./Installers:/app/Installers:ro
      - ./Licenses:/app/licenses
     #- ./Licenses/server.prvc:/app/server.prvc:ro
      - ./configurebasedeployment.properties:/app/configurebasedeployment.properties:rw
      - "./shared:/shared:rw"
      - "./ubuntu-server/charles.pem:/tmp/charles.pem:ro"
      # important: this affects Docker-in-Docker mounting, paths under named volumes cannot be used directly
      # /home/arcgis -> /var/lib/docker/volumes/arcgis_test_home/_data
      # - test_home:/home/arcgis:rw
      # mounting actual path from WSL host (for DinD)
      - /home/arcgis:/home/arcgis:rw
      - test_data:/data:rw
      #- /sys/fs/cgroup:/sys/fs/cgroup:rw
      # important: enable below if using WSL2
      - /var/run/docker.sock:/var/run/docker.sock
     # - server_data:/srv/directories:rw
#      - server_config:/home/arcgis/server/usr/config-store
#      - server_logs:/home/arcgis/server/usr/logs
    # Uncomment the next three lines to work in a shell environment for debugging. (See exec_server)
    # entrypoint: /bin/bash
    # stdin_open: true
    # tty: true