# Change prompt
export PS1="ArcGIS Server$ "

# Add the Server binaries to the PATH
PATH=$PATH:$HOME/server:$HOME/server/tools:$HOME/server/tools/configurebasedeployment


# In Portal, each tool is in a separate folder in
# tools/ -- bad idea.. whatever.. there are more tools
# these are just the ones I added today.
PATH=$PATH:$HOME/portal:\
$HOME/portal/framework/etc:\
$HOME/portal/tools/accountmanagement:\
$HOME/portal/tools/createportal:\
$HOME/portal/tools/operationalhealth:\
$HOME/portal/tools/importlicense:\
$HOME/portal/tools/indexer:\
$HOME/portal/tools/portaldiag:\
$HOME/portal/tools/webgisdr

export PATH
